/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.java.desktop_java;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.event.*;
/**
 *
 * @author Achraf
 */
public class demandeNonTraite extends javax.swing.JFrame {
    String CNE = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    int tabSel =0;
    DefaultTableModel model;
    /**
     * Creates new form demandeNonTraite
     */
    public demandeNonTraite() {
        initComponents();
      TableConventionStage();
      TableReleveNote();
      TableAttestationScolarite();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        deconnecter = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        retour = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConvensionTable = new javax.swing.JTable();
        search_conv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        saved = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        AttestationTable = new javax.swing.JTable();
        search_attest = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ReleveTable = new javax.swing.JTable();
        search_releve = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        deconnecter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deconnecter.setForeground(new java.awt.Color(0, 102, 102));
        deconnecter.setText("Se deconnecter");

        menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu.setForeground(new java.awt.Color(0, 102, 102));
        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        retour.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        retour.setForeground(new java.awt.Color(0, 102, 102));
        retour.setText("Retour");
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(deconnecter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retour, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(retour)
                .addGap(99, 99, 99)
                .addComponent(menu)
                .addGap(18, 18, 18)
                .addComponent(deconnecter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 153));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        ConvensionTable.setBackground(new java.awt.Color(0, 102, 102));
        ConvensionTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ConvensionTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ConvensionTable.setForeground(new java.awt.Color(255, 255, 255));
        ConvensionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNE", "Nom", "Prenom", "Email", "date demande"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ConvensionTable.setMinimumSize(new java.awt.Dimension(200, 40));
        ConvensionTable.setSelectionBackground(new java.awt.Color(0, 153, 153));
        ConvensionTable.getTableHeader().setResizingAllowed(false);
        ConvensionTable.getTableHeader().setReorderingAllowed(false);
        ConvensionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConvensionTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ConvensionTable);

        search_conv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_convActionPerformed(evt);
            }
        });
        search_conv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_convKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("CNE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_conv, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saved, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_conv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(saved)
                        .addGap(199, 199, 199))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Convension de stage", jPanel4);

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        AttestationTable.setBackground(new java.awt.Color(0, 102, 102));
        AttestationTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AttestationTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AttestationTable.setForeground(new java.awt.Color(255, 255, 255));
        AttestationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"S12343213", "amagarou", "fatima zahrae", "fatimazahrae@gmail.com", "05/12/2022"}
            },
            new String [] {
                "CNE", "Nom", "Prenom", "Email", "date demande"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AttestationTable.setGridColor(new java.awt.Color(0, 0, 0));
        AttestationTable.setMinimumSize(new java.awt.Dimension(200, 20));
        AttestationTable.setSelectionBackground(new java.awt.Color(0, 153, 153));
        AttestationTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        AttestationTable.getTableHeader().setResizingAllowed(false);
        AttestationTable.getTableHeader().setReorderingAllowed(false);
        AttestationTable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AttestationTableMouseMoved(evt);
            }
        });
        AttestationTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AttestationTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(AttestationTable);

        search_attest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_attestKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("CNE");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_attest, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 251, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_attest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Attestation de scholarite", jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        ReleveTable.setBackground(new java.awt.Color(0, 102, 102));
        ReleveTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ReleveTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ReleveTable.setForeground(new java.awt.Color(255, 255, 255));
        ReleveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"k453636", "moussaoui", "farah", "moussaoui@gmail.com", "03/12/2022"}
            },
            new String [] {
                "CNE", "Nom", "Prenom", "Email", "date demande"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ReleveTable.setMinimumSize(new java.awt.Dimension(200, 20));
        ReleveTable.setSelectionBackground(new java.awt.Color(0, 153, 153));
        ReleveTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReleveTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(ReleveTable);

        search_releve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_releveActionPerformed(evt);
            }
        });
        search_releve.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_releveKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("CNE");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_releve, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 252, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_releve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relever de note", jPanel7);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //ConvensionTable
    private void ConvensionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConvensionTableMouseClicked
                 // TODO add your handling code here:
         try {
             
            int i = ConvensionTable.getSelectedRow();
            
            TableModel tm =ConvensionTable.getModel();   
            
            CNE =tm.getValueAt(i, 0).toString();
            
            //************************************
            try {
            ps = (PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select id from gl_projet.etudiants where cne=?");
            ps.setString(1,CNE);
            rs = ps.executeQuery();
            int id=0;           
            if(rs.next()){
              id = rs.getInt("id");
             
              ps = (PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select id_demande  from gl_projet.demande_docs where id_etudiant=?  and date_demande=?");
              ps.setInt(1,id);   
              ps.setString(2,tm.getValueAt(i, 4).toString());
              rs = ps.executeQuery();
              int id_demande;
             
              if(rs.next()){   
                  id_demande=rs.getInt("id_demande");
                  ConventionStage a = new ConventionStage(id_demande,id);
                  a.setVisible(true);
                   this.dispose();
              } 
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed 1!!!");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed 2");
        }
    }//GEN-LAST:event_ConvensionTableMouseClicked

    private void AttestationTableMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttestationTableMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_AttestationTableMouseMoved
/*
    private void AttestationTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttestationTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AttestationTableMouseClicked

    private void ReleveTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReleveTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ReleveTableMouseClicked

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_retourActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void search_releveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_releveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_releveActionPerformed
*/
    private void search_releveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_releveKeyReleased
        // TODO add your handling code here:
        String SearchString = search_releve.getText();
        search3(SearchString);
    }//GEN-LAST:event_search_releveKeyReleased

    private void search_attestKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_attestKeyReleased
        // TODO add your handling code here:
        String SearchString = search_attest.getText();
        search2(SearchString);
    }//GEN-LAST:event_search_attestKeyReleased

    private void search_convKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_convKeyReleased
        // TODO add your handling code here:
        String SearchString = search_conv.getText();
        search(SearchString);
    }//GEN-LAST:event_search_convKeyReleased

    private void search_convActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_convActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_convActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
       Demande_archive ar = new Demande_archive();
       ar.setVisible(true);
       this.dispose();   
    }  
    private void retourActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
       Demande_archive ar = new Demande_archive();
       ar.setVisible(true);
       this.dispose();   
    }    
    //AttestationTable
    private void AttestationTableMouseClicked(java.awt.event.MouseEvent evt) {                                             
                 // TODO add your handling code here:
         try {
             
            int i = AttestationTable.getSelectedRow();
            //ok.setText( Integer.toString(i));
            TableModel tm =AttestationTable.getModel();   
            
            CNE =tm.getValueAt(i, 0).toString();
            //ok.setText( CNE);
            //************************************
            try {
            ps = (PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select id from gl_projet.etudiants where cne=?");
            ps.setString(1,CNE);
            rs = ps.executeQuery();
            int id=0;           
            if(rs.next()){
              id = rs.getInt("id");
             //ok.setText(Integer.toString(id));
             //ok.setText(tm.getValueAt(i, 4).toString());
              ps = (PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select id_demande  from gl_projet.demande_docs where id_etudiant=?  and date_demande=?");
              ps.setInt(1,id);   
              ps.setString(2,tm.getValueAt(i, 4).toString()); 
              rs = ps.executeQuery();
               
              int id_demande;
              if(rs.next()){ 
                  //JOptionPane.showMessageDialog(null, "connection ");
                  id_demande=rs.getInt("id_demande");
                  AttestationScolarite a = new AttestationScolarite(id_demande,id);
                  a.setVisible(true);
                  this.dispose();
              } 
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed 1!!!");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed 2");
        }
    }          
    //ReleverTable
        private void ReleveTableMouseClicked(java.awt.event.MouseEvent evt){                                             
                 // TODO add your handling code here:
         try {
             
            int i = ReleveTable.getSelectedRow();
            TableModel tm =ReleveTable.getModel();   
            
            CNE =tm.getValueAt(i, 0).toString();
            
            //************************************
            try {
            ps = (PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select id from gl_projet.etudiants where cne=?");
            ps.setString(1,CNE);
            rs = ps.executeQuery();
            int id=0;           
            if(rs.next()){
              id = rs.getInt("id");
             
              ps = (PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select id_demande  from gl_projet.demande_docs where id_etudiant=?  and date_demande=?");
              ps.setInt(1,id);   
              ps.setString(2,tm.getValueAt(i, 4).toString());
              rs = ps.executeQuery();
              int id_demande;
             
              if(rs.next()){   
                  id_demande=rs.getInt("id_demande");
                  ReleveNote a = new ReleveNote(id_demande,id);
                   a.setVisible(true);
                   this.dispose();
              } 
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed 1!!!");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed 2");
        }
    }
        public void TableConventionStage(){
     String enregistrer [] = {"CNE","Prénom","Nom","Email"};
     String afficher[] = new String[5];
     DefaultTableModel model = new DefaultTableModel(null,enregistrer);
     try{
          PreparedStatement ps;
          ps = ConnectionDB.getConnexion().prepareStatement("select * from gl_projet.demande_docs where is_archive=? and type_demande=?");
          ps.setString(1,"0");
          ps.setString(2,"convention stage");
          ResultSet rs = ps.executeQuery();
        while(rs.next()){
             afficher[4]=rs.getString("date_demande");
            int id_etud = rs.getInt("id_etudiant");
             PreparedStatement ps2 =  ConnectionDB.getConnexion().prepareStatement("select * from gl_projet.etudiants where id=?");
             ps2.setString(1, Integer.toString(id_etud));
             ResultSet rs2 = ps2.executeQuery();

             if(rs2.next()){
                afficher[0]=rs2.getString("cne");
                afficher[1]=rs2.getString("prenom");
                afficher[2]=rs2.getString("nom"); 
                afficher[3]=rs2.getString("email_etudiant");   
             }
             model.addRow(afficher);
        }
        ConvensionTable.setModel(model);
     }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed!!!");
        }
    }
       public void TableAttestationScolarite(){
     String enregistrer [] = {"CNE","Prénom","Nom","Email"};
     String afficher[] = new String[5];
     DefaultTableModel model = new DefaultTableModel(null,enregistrer);
     try{
          PreparedStatement ps;
          ps = ConnectionDB.getConnexion().prepareStatement("select * from gl_projet.demande_docs where is_archive=? and type_demande=? ");
          ps.setString(1,"0");
          ps.setString(2,"attestation scolarite");
          ResultSet rs = ps.executeQuery();
        while(rs.next()){
            afficher[4]=rs.getString("date_demande");
            int id_etud = rs.getInt("id_etudiant");
             PreparedStatement ps2 =  ConnectionDB.getConnexion().prepareStatement("select * from gl_projet.etudiants where id=? ");
             ps2.setString(1, Integer.toString(id_etud));
             ResultSet rs2 = ps2.executeQuery();
             if(rs2.next()){
                afficher[0]=rs2.getString("cne");
                afficher[1]=rs2.getString("prenom");
                afficher[2]=rs2.getString("nom"); 
                afficher[3]=rs2.getString("email_etudiant");   
             }
             model.addRow(afficher);
        }
        AttestationTable.setModel(model);
     }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed!!!");
        }
    }
       public void TableReleveNote(){
     String enregistrer [] = {"CNE","Prénom","Nom","Email"};
     String afficher[] = new String[5];
     DefaultTableModel model = new DefaultTableModel(null,enregistrer);
     try{
          PreparedStatement ps;
          ps = ConnectionDB.getConnexion().prepareStatement("select * from gl_projet.demande_docs where is_archive=? and type_demande=?");
          ps.setString(1,"0");
          ps.setString(2,"releve de notes");
          ResultSet rs = ps.executeQuery();
        while(rs.next()){    
            afficher[4]=rs.getString("date_demande");
            int id_etud = rs.getInt("id_etudiant");
            PreparedStatement ps2 =  ConnectionDB.getConnexion().prepareStatement("select * from gl_projet.etudiants where id=?");
            ps2.setString(1, Integer.toString(id_etud));
            ResultSet rs2 = ps2.executeQuery();

             if(rs2.next()){
                afficher[0]=rs2.getString("cne");
                afficher[1]=rs2.getString("prenom");
                afficher[2]=rs2.getString("nom"); 
                afficher[3]=rs2.getString("email_etudiant");   
             }
             model.addRow(afficher);
        }
        ReleveTable.setModel(model);
     }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed!!!");
        }
    }
       public void search(String str){
        model = (DefaultTableModel)ConvensionTable .getModel();
        TableRowSorter<DefaultTableModel>trs = new TableRowSorter<>(model);
        ConvensionTable.setRowSorter(trs);      
        trs.setRowFilter(RowFilter.regexFilter(str));
    }
       public void search2(String str){
        model = (DefaultTableModel)AttestationTable .getModel();
        TableRowSorter<DefaultTableModel>trs = new TableRowSorter<>(model);
        AttestationTable.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }
       public void search3(String str){
        model = (DefaultTableModel)ReleveTable.getModel();
        TableRowSorter<DefaultTableModel>trs = new TableRowSorter<>(model);
        ReleveTable.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demandeNonTraite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demandeNonTraite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demandeNonTraite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demandeNonTraite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new demandeNonTraite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AttestationTable;
    private javax.swing.JTable ConvensionTable;
    private javax.swing.JTable ReleveTable;
    private javax.swing.JButton deconnecter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton menu;
    private javax.swing.JButton retour;
    private javax.swing.JLabel saved;
    private javax.swing.JTextField search_attest;
    private javax.swing.JTextField search_conv;
    private javax.swing.JTextField search_releve;
    // End of variables declaration//GEN-END:variables
}
