/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.java.desktop_java;
import com.spire.doc.*;
import com.spire.doc.documents.*;  
import com.spire.doc.fields.*;  
import java.awt.*;
import java.io.*;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import java.util.*;
import javax.activation.*;
import javax.mail.Authenticator;
import javax.mail.*;
import javax.mail.PasswordAuthentication;
import javax.swing.JOptionPane;
import javax.mail.Session;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.*;
import javax.swing.JPanel;


/**
 *
 * @author Achraf
 */
public class pourTestFiles extends javax.swing.JFrame {

    int id=4;
    int id_demande=1;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    ResultSet rs1 = null;
    PreparedStatement pst1 = null;
    /**
     * Creates new form pourTestFiles
     */
    public pourTestFiles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        generate = new javax.swing.JButton();
        relever_note = new javax.swing.JButton();
        generate1 = new javax.swing.JButton();
        generate2 = new javax.swing.JButton();
        generate3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Email");

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        generate.setText("Attestation");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        relever_note.setText("Semester 1");
        relever_note.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relever_noteActionPerformed(evt);
            }
        });

        generate1.setText("Semester 2");
        generate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate1ActionPerformed(evt);
            }
        });

        generate2.setText("tous les semesters");
        generate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate2ActionPerformed(evt);
            }
        });

        generate3.setText("convension");
        generate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(generate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(relever_note, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generate3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {generate, generate1, generate2, relever_note});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(relever_note)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generate1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generate2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generate3)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    static void replaceTextinDocumentBody(Map<String, String> map, Document document){  
        for(Section section : (Iterable<Section>)document.getSections()) {  
            for (Paragraph para : (Iterable<Paragraph>) section.getParagraphs()) {  
                for (Map.Entry<String, String> entry : map.entrySet()) {  
                    para.replace("${" + entry.getKey() + "}", entry.getValue(), false, true);  
                }  
            }  
        }  
    }
    static  void replaceTextWithImage(Document document, String stringToReplace, String imagePath){  
        TextSelection[] selections = document.findAllString("${" + stringToReplace + "}", false, true);  
        int index = 0;  
        TextRange range = null;  
        for (Object obj : selections) {  
            TextSelection textSelection = (TextSelection)obj;  
            DocPicture pic = new DocPicture(document);  
            pic.loadImage(imagePath);
            
            range = textSelection.getAsOneRange();  
            index = range.getOwnerParagraph().getChildObjects().indexOf(range);  
            range.getOwnerParagraph().getChildObjects().insert(index,pic);  
            range.getOwnerParagraph().getChildObjects().remove(range);  
        }  
    }
    static void replaceTextinTable(Map<String, String> map, Table table){  
        for(TableRow row:(Iterable<TableRow>)table.getRows()){  
            for(TableCell cell : (Iterable<TableCell>)row.getCells()){  
                for(Paragraph para : (Iterable<Paragraph>)cell.getParagraphs()){  
                    for (Map.Entry<String, String> entry : map.entrySet()) {  
                        para.replace("${" + entry.getKey() + "}", entry.getValue(), false, true);  
                    }  
                }  
            }  
        }  
    } 
    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
            
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "achraf");
        pst =(PreparedStatement) conn.prepareStatement("select * from etudiants,demande_docs,attestation_scolarites where etudiants.id=demande_docs.id_etudiant and attestation_scolarites.id=demande_docs.id_demande and etudiants.id=? and demande_docs.id=? ;");
        pst.setString(1, Integer.toString(id));
        pst.setString(2, Integer.toString(id_demande));
        rs = pst.executeQuery();
        rs.next();
        
        
        String email = Email.getText();
        //String email = rs.getString("email_etudiant");

        String date = java.time.LocalDate.now().toString();
        String nom = rs.getString("nom");
        String prenom = rs.getString("prenom");
        String cne = rs.getString("cne");
        String apogee = rs.getString("code_apogee");
        String filiere  = rs.getString("filiere");
        String année = "2022/2023";
        //String année = rs.getString("annee_universitaire");
        
        
        String signature = "D:\\javadirectories\\signatures\\signature.png";
        
        
        String bodymessage="Votre Attestation de scolarite est pris";
       
        Document document = new Document("D:\\javadirectories\\attestation.docx");
        //Document document = new Document("/attestation.docx");
        
        Map<String, String> map = new HashMap<String, String>();  
        
        map.put("date",date);
        map.put("nom",nom);
        map.put("prenom",prenom);
        map.put("cne",cne);
        map.put("apogee",apogee);
        map.put("filiere",filiere);
        map.put("année",année);
        
        replaceTextinDocumentBody(map,document);
        
        replaceTextWithImage(document, "signature", signature);
              
        
        String pathpdf ="D:\\javadirectories\\repos\\attestation_"+apogee+"_"+rs.getString("id_demande")+".pdf";
        String path ="D:\\javadirectories\\repos\\attestation_"+apogee+"_"+rs.getString("id_demande")+".docx";
        //document.saveToFile(path, FileFormat.PDF);
        document.saveToFile(path, FileFormat.Docx);
        
        //word to pdf
        /*
        Document documentpdf = new Document(path);
        documentpdf.saveToFile(path, FileFormat.PDF);*/
        Document doc = new Document();
        //Load a sample Word document
        doc.loadFromFile(path);
        //Create a ToPdfParameterList instance
        ToPdfParameterList ppl=new ToPdfParameterList();
        //Embed all fonts in the PDF document
        ppl.isEmbeddedAllFonts(true);
        //Remove the hyperlinks and keep the character formats
        ppl.setDisableLink(true);
        //Set the output image quality as 40% of the original image. 80% is the default setting.
        doc.setJPEGQuality(40);
        //Save the document as PDF
        doc.saveToFile(pathpdf, ppl);
        
        File f = new File(path);
        f.delete();
        
        JOptionPane.showMessageDialog(null, "File generated, path : "+pathpdf);
        
        //archiver
        pst =(PreparedStatement) conn.prepareStatement("UPDATE demande_docs SET status='accepté', is_archive=1 WHERE id=? ;");
        pst.setString(1, Integer.toString(id_demande));
        pst.executeUpdate();
        
        
        //open pdf fine
        File myFile = new File(pathpdf);
        Desktop.getDesktop().open(myFile);
        
        
        //variable de email
        String subject = "Tester email";
        String myAdress = "porjetgenie.logiciel2022@gmail.com";
        String passwordEMail = "genielogiciel";
        String contenue = bodymessage;
        String otherEmail = email;
        //send file in email code
        Properties properties = new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");
        Session session = Session.getDefaultInstance(properties,new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication("porjetgenie.logiciel2022@gmail.com","trbqpsgfwezksylh");
            }
            
        });
        Message message = new MimeMessage(session);
        message.setSubject(subject);
        //message.setContent(other,"text/plain");
        message.setFrom(new InternetAddress(myAdress));
        message.setRecipient(Message.RecipientType.TO, new InternetAddress(email));
        message.setSentDate(new java.util.Date());
        
        // Create the message part 
            BodyPart messageBodyPart = new MimeBodyPart();

            // Fill the message
            messageBodyPart.setText(bodymessage);
            // Create a multipar message
            Multipart multipart = new MimeMultipart();
            
            // Set text message part
            multipart.addBodyPart(messageBodyPart);

            // Part two is attachment
            messageBodyPart = new MimeBodyPart();
            String filename = pathpdf;
            DataSource source = new FileDataSource(filename);
            messageBodyPart.setDataHandler(new DataHandler(source));
            messageBodyPart.setFileName(filename);
            multipart.addBodyPart(messageBodyPart);

            // Send the complete message parts
            message.setContent(multipart);

            Transport.send(message);
        JOptionPane.showMessageDialog(null, "email sent");
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
                //Create a Word document
        
        
    }//GEN-LAST:event_generateActionPerformed

    private void relever_noteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relever_noteActionPerformed
        // TODO add your handling code here:
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
            
    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "achraf");
    pst1 =(PreparedStatement) conn.prepareStatement("select * from modules,etudiants,modules_etudiants,demande_docs where etudiants.id=modules_etudiants.id_etudiant and modules.id=modules_etudiants.id_module and modules.niveau=? and etudiants.id=? and demande_docs.id=?; ");
    //pst1.setString(2, Integer.toString(id));
    String niveau="2AP1";
    String semester ="1";
    String conca = niveau+semester;
    pst1.setString(1,conca);
    pst1.setString(2,Integer.toString(id));
    pst1.setString(3,Integer.toString(id_demande));
    rs1 = pst1.executeQuery();
    Document document = new Document("D:\\javadirectories\\releve_de_notes.docx"); 
    Section section = document.getSections().get(0);  
    Table table = section.getTables().get(0);
    //Section section1 = document.getSections().get(0);  
    Table table1 = section.getTables().get(1);
    
    Map<String, String> map = new HashMap<String, String>(); 

    rs1.next();
    String a = rs1.getString("nom");
    map.put("nom",a);
    
    map.put("prenom",rs1.getString("prenom"));
    map.put("date_nai",rs1.getString("annee_naissance"));
    map.put("adress",rs1.getString("adresse"));
    map.put("filiere",rs1.getString("filiere"));
    map.put("apogee",rs1.getString("code_apogee"));
    map.put("cne",rs1.getString("cne"));
    //map.put("annee_univ",rs1.getString("annee_universitaire"));
    map.put("date",java.time.LocalDate.now().toString());
        

    /**************************************/
    map.put("module1",rs1.getString("intitule"));
    map.put("note1",rs1.getString("note"));
    map.put("status1",rs1.getString("status"));
    rs1.next();
    map.put("module2",rs1.getString("intitule"));
    map.put("note2",rs1.getString("note"));
    map.put("status2",rs1.getString("status"));
    rs1.next();
    map.put("module3",rs1.getString("intitule"));
    map.put("note3",rs1.getString("note"));
    map.put("status3",rs1.getString("status"));
    
    replaceTextinDocumentBody(map,document);
    replaceTextinTable(map,table);
    replaceTextinTable(map,table1);
    
    String path ="D:\\javadirectories\\repos\\relever_note_"+rs1.getString("code_apogee")+"_"+rs1.getString("id_demande")+".pdf";
    document.saveToFile(path, FileFormat.PDF);
    JOptionPane.showMessageDialog(null, "File generated, path : "+path);
    
    //archiver
    pst1 =(PreparedStatement) conn.prepareStatement("UPDATE demande_docs SET status='accepté', is_archive=1 WHERE id=? ;");
    pst1.setString(1, Integer.toString(id_demande));
    pst1.executeUpdate();
    //open pdf fine
        File myFile = new File(path);
        Desktop.getDesktop().open(myFile);
        
        
        //variable de email
        String email = Email.getText();
        //String email = rs.getString("email_etudiant");
        String bodymessage = "Votre relever de note";
        String subject = "Tester email";
        String myAdress = "porjetgenie.logiciel2022@gmail.com";
        String passwordEMail = "genielogiciel";
        String contenue = bodymessage;
        String otherEmail = email;
        //send file in email code
        Properties properties = new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");
        Session session = Session.getDefaultInstance(properties,new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication("porjetgenie.logiciel2022@gmail.com","trbqpsgfwezksylh");
            }
            
        });
        Message message = new MimeMessage(session);
        message.setSubject(subject);
        //message.setContent(other,"text/plain");
        message.setFrom(new InternetAddress(myAdress));
        message.setRecipient(Message.RecipientType.TO, new InternetAddress(email));
        message.setSentDate(new java.util.Date());
        
        // Create the message part 
            BodyPart messageBodyPart = new MimeBodyPart();

            // Fill the message
            messageBodyPart.setText(bodymessage);
            // Create a multipar message
            Multipart multipart = new MimeMultipart();
            
            // Set text message part
            multipart.addBodyPart(messageBodyPart);

            // Part two is attachment
            messageBodyPart = new MimeBodyPart();
            String filename = path;
            DataSource source = new FileDataSource(filename);
            messageBodyPart.setDataHandler(new DataHandler(source));
            messageBodyPart.setFileName(filename);
            multipart.addBodyPart(messageBodyPart);

            // Send the complete message parts
            message.setContent(multipart);

            Transport.send(message);
        JOptionPane.showMessageDialog(null, "email sent");
    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }try {
    Class.forName("com.mysql.cj.jdbc.Driver");
            
    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "achraf");
    pst1 =(PreparedStatement) conn.prepareStatement("select * from modules,etudiants,modules_etudiants where etudiants.id=modules_etudiants.id_etudiant and modules.id=modules_etudiants.id_module and modules.niveau=? and etudiants.id=?; ");
    //pst1.setString(2, Integer.toString(id));
    String niveau="2AP1";
    String semester ="1";
    String conca = niveau+semester;
    pst1.setString(1,conca);
    pst1.setString(2,Integer.toString(id));
    rs1 = pst1.executeQuery();
    Document document = new Document("D:\\javadirectories\\releve_de_notes.docx"); 
    Section section = document.getSections().get(0);  
    Table table = section.getTables().get(0);
    //Section section1 = document.getSections().get(0);  
    Table table1 = section.getTables().get(1);
    
    Map<String, String> map = new HashMap<String, String>(); 

    rs1.next();
    String a = rs1.getString("nom");
    map.put("nom",a);
    
    map.put("prenom",rs1.getString("prenom"));
    map.put("date_nai",rs1.getString("annee_naissance"));
    map.put("adress",rs1.getString("adresse"));
    map.put("filiere",rs1.getString("filiere"));
    map.put("apogee",rs1.getString("code_apogee"));
    map.put("cne",rs1.getString("cne"));
    //map.put("annee_univ",rs1.getString("annee_universitaire"));
    map.put("date",java.time.LocalDate.now().toString());
        

    /**************************************/
    map.put("module1",rs1.getString("intitule"));
    map.put("note1",rs1.getString("note"));
    map.put("status1",rs1.getString("status"));
    rs1.next();
    map.put("module2",rs1.getString("intitule"));
    map.put("note2",rs1.getString("note"));
    map.put("status2",rs1.getString("status"));
    rs1.next();
    map.put("module3",rs1.getString("intitule"));
    map.put("note3",rs1.getString("note"));
    map.put("status3",rs1.getString("status"));
    
    replaceTextinDocumentBody(map,document);
    replaceTextinTable(map,table);
    replaceTextinTable(map,table1);
    
    String path ="D:\\javadirectories\\repos\\relever_note_"+rs1.getString("code_apogee")+"_"+rs1.getString("id_demande")+".pdf";
    document.saveToFile(path, FileFormat.PDF);
    JOptionPane.showMessageDialog(null, "File generated, path : "+path);

    
    //open pdf fine
    File myFile = new File(path);
    Desktop.getDesktop().open(myFile);
    
    
    //variable de email
    String email = Email.getText();
    //String email = rs.getString("email_etudiant");
    String bodymessage = "Votre relever de note";
    String subject = "Tester email";
    String myAdress = "porjetgenie.logiciel2022@gmail.com";
    String passwordEMail = "genielogiciel";
    String contenue = bodymessage;
    String otherEmail = email;
    //send file in email code
    Properties properties = new Properties();
    properties.put("mail.smtp.auth", "true");
    properties.put("mail.smtp.starttls.enable", "true");
    properties.put("mail.smtp.host", "smtp.gmail.com");
    properties.put("mail.smtp.port", "587");
    Session session = Session.getDefaultInstance(properties,new Authenticator() {
        @Override
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication("porjetgenie.logiciel2022@gmail.com","trbqpsgfwezksylh");
        }
        
    });
    Message message = new MimeMessage(session);
    message.setSubject(subject);
    //message.setContent(other,"text/plain");
    message.setFrom(new InternetAddress(myAdress));
    message.setRecipient(Message.RecipientType.TO, new InternetAddress(email));
    message.setSentDate(new java.util.Date());
    
    // Create the message part 
    BodyPart messageBodyPart = new MimeBodyPart();
    // Fill the message
    messageBodyPart.setText(bodymessage);
    // Create a multipar message
    Multipart multipart = new MimeMultipart();
    
    // Set text message part
    multipart.addBodyPart(messageBodyPart);
    // Part two is attachment
    messageBodyPart = new MimeBodyPart();
    String filename = path;
    DataSource source = new FileDataSource(filename);
    messageBodyPart.setDataHandler(new DataHandler(source));
    messageBodyPart.setFileName(filename);
    multipart.addBodyPart(messageBodyPart);
    // Send the complete message parts
    message.setContent(multipart);
    Transport.send(message);


    JOptionPane.showMessageDialog(null, "email sent");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    
    
    }//GEN-LAST:event_relever_noteActionPerformed

    private void generate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate1ActionPerformed
        // TODO add your handling code here:
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
            
    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "achraf");
    pst1 =(PreparedStatement) conn.prepareStatement("select * from modules,etudiants,modules_etudiants,demande_docs where etudiants.id=modules_etudiants.id_etudiant and modules.id=modules_etudiants.id_module and modules.niveau=? and etudiants.id=? and demande_docs.id=?; ");
    String niveau="2AP1";
    String semester ="2";
    String conca = niveau+semester;
    pst1.setString(1,conca);
    pst1.setString(2,Integer.toString(id));
    pst1.setString(3,Integer.toString(id_demande));
    rs1 = pst1.executeQuery();
    Document document = new Document("D:\\javadirectories\\releve_de_notes_2.docx"); 
    Section section = document.getSections().get(0);  
    Table table = section.getTables().get(0);
    //Section section1 = document.getSections().get(0);  
    Table table1 = section.getTables().get(1);
    
    Map<String, String> map = new HashMap<String, String>(); 

    rs1.next();
    String a = rs1.getString("nom");
    map.put("nom",a);
    
    map.put("prenom",rs1.getString("prenom"));
    map.put("date_nai",rs1.getString("annee_naissance"));
    map.put("adress",rs1.getString("adresse"));
    map.put("filiere",rs1.getString("filiere"));
    map.put("apogee",rs1.getString("code_apogee"));
    map.put("cne",rs1.getString("cne"));
    //map.put("annee_univ",rs1.getString("annee_universitaire"));
    map.put("date",java.time.LocalDate.now().toString());
        

    /**************************************/
    map.put("module1",rs1.getString("intitule"));
    map.put("note1",rs1.getString("note"));
    map.put("status1",rs1.getString("status"));
    rs1.next();
    map.put("module2",rs1.getString("intitule"));
    map.put("note2",rs1.getString("note"));
    map.put("status2",rs1.getString("status"));
    rs1.next();
    map.put("module3",rs1.getString("intitule"));
    map.put("note3",rs1.getString("note"));
    map.put("status3",rs1.getString("status"));
    
    replaceTextinDocumentBody(map,document);
    replaceTextinTable(map,table);
    replaceTextinTable(map,table1);
    
    String path ="D:\\javadirectories\\repos\\relever_note_2_"+rs1.getString("code_apogee")+"_"+rs1.getString("id_demande")+".pdf";
    document.saveToFile(path, FileFormat.PDF);
    JOptionPane.showMessageDialog(null, "File generated, path : "+path);

    //archiver
    pst1 =(PreparedStatement) conn.prepareStatement("UPDATE demande_docs SET status='accepté', is_archive=1 WHERE id=? ;");
    pst1.setString(1, Integer.toString(id_demande));
    pst1.executeUpdate();
    //open pdf fine
    File myFile = new File(path);
    Desktop.getDesktop().open(myFile);
    
    
    //variable de email
    String email = Email.getText();
    //String email = rs.getString("email_etudiant");
    String bodymessage = "Votre relever de note";
    String subject = "Tester email";
    String myAdress = "porjetgenie.logiciel2022@gmail.com";
    String passwordEMail = "genielogiciel";
    String contenue = bodymessage;
    String otherEmail = email;
    //send file in email code
    Properties properties = new Properties();
    properties.put("mail.smtp.auth", "true");
    properties.put("mail.smtp.starttls.enable", "true");
    properties.put("mail.smtp.host", "smtp.gmail.com");
    properties.put("mail.smtp.port", "587");
    Session session = Session.getDefaultInstance(properties,new Authenticator() {
        @Override
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication("porjetgenie.logiciel2022@gmail.com","trbqpsgfwezksylh");
        }
        
    });
    Message message = new MimeMessage(session);
    message.setSubject(subject);
    //message.setContent(other,"text/plain");
    message.setFrom(new InternetAddress(myAdress));
    message.setRecipient(Message.RecipientType.TO, new InternetAddress(email));
    message.setSentDate(new java.util.Date());
    
    // Create the message part 
    BodyPart messageBodyPart = new MimeBodyPart();
    // Fill the message
    messageBodyPart.setText(bodymessage);
    // Create a multipar message
    Multipart multipart = new MimeMultipart();
    
    // Set text message part
    multipart.addBodyPart(messageBodyPart);
    // Part two is attachment
    messageBodyPart = new MimeBodyPart();
    String filename = path;
    DataSource source = new FileDataSource(filename);
    messageBodyPart.setDataHandler(new DataHandler(source));
    messageBodyPart.setFileName(filename);
    multipart.addBodyPart(messageBodyPart);
    // Send the complete message parts
    message.setContent(multipart);
    Transport.send(message);


    JOptionPane.showMessageDialog(null, "email sent");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_generate1ActionPerformed

    private void generate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate2ActionPerformed
        // TODO add your handling code here:
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
            
    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "achraf");
    pst1 =(PreparedStatement) conn.prepareStatement("select * from etudiants,modules,modules_etudiants,demande_docs where etudiants.id=modules_etudiants.id_etudiant and modules.id=modules_etudiants.id_module and etudiants.id=? and modules.niveau in (select concat(releve_notes.niveau,releve_notes.semestre) as v_niveau from releve_notes,etudiants,demande_docs where demande_docs.id_demande=releve_notes.id and etudiants.id=demande_docs.id_etudiant and etudiants.id=?);");
    pst1.setString(1,Integer.toString(id));
    pst1.setString(2,Integer.toString(id));
    rs1 = pst1.executeQuery();
    Document document = new Document("D:\\javadirectories\\releve_de_notes_t.docx"); 
    Section section = document.getSections().get(0);  
    Table table = section.getTables().get(0); 
    Table table1 = section.getTables().get(1);
    Table table2 = section.getTables().get(2);
    
    Map<String, String> map = new HashMap<String, String>(); 

    rs1.next();
    map.put("nom",rs1.getString("nom"));
    
    map.put("prenom",rs1.getString("prenom"));
    map.put("date_nai",rs1.getString("annee_naissance"));
    map.put("adress",rs1.getString("adresse"));
    map.put("filiere",rs1.getString("filiere"));
    map.put("apogee",rs1.getString("code_apogee"));
    map.put("cne",rs1.getString("cne"));
    map.put("date",java.time.LocalDate.now().toString());
        

    /**************************************/
    map.put("module1",rs1.getString("intitule"));
    map.put("note1",rs1.getString("note"));
    map.put("status1",rs1.getString("status"));
    rs1.next();
    map.put("module2",rs1.getString("intitule"));
    map.put("note2",rs1.getString("note"));
    map.put("status2",rs1.getString("status"));
    rs1.next();
    map.put("module3",rs1.getString("intitule"));
    map.put("note3",rs1.getString("note"));
    map.put("status3",rs1.getString("status"));
    rs1.next();
    map.put("module4",rs1.getString("intitule"));
    map.put("note4",rs1.getString("note"));
    map.put("status4",rs1.getString("status"));
    rs1.next();
    map.put("module5",rs1.getString("intitule"));
    map.put("note5",rs1.getString("note"));
    map.put("status5",rs1.getString("status"));
    rs1.next();
    map.put("module6",rs1.getString("intitule"));
    map.put("note6",rs1.getString("note"));
    map.put("status6",rs1.getString("status"));
    
    replaceTextinDocumentBody(map,document);
    replaceTextinTable(map,table);
    replaceTextinTable(map,table1);
    replaceTextinTable(map,table2);
    
    String path ="D:\\javadirectories\\repos\\relever_note_t_"+rs1.getString("code_apogee")+rs1.getString("id_demande")+".pdf";
    document.saveToFile(path, FileFormat.PDF);
    JOptionPane.showMessageDialog(null, "File generated, path : "+path);

    //archiver
    pst1 =(PreparedStatement) conn.prepareStatement("UPDATE demande_docs SET status='accepté', is_archive=1 WHERE id=? ;");
    pst1.setString(1, Integer.toString(id_demande));
    pst1.executeUpdate();
    //open pdf fine
    File myFile = new File(path);
    Desktop.getDesktop().open(myFile);
    
    
    //variable de email
    String email = Email.getText();
    //String email = rs.getString("email_etudiant");
    String bodymessage = "Votre relever de note";
    String subject = "Tester email";
    String myAdress = "porjetgenie.logiciel2022@gmail.com";
    String passwordEMail = "genielogiciel";
    String contenue = bodymessage;
    String otherEmail = email;
    //send file in email code
    Properties properties = new Properties();
    properties.put("mail.smtp.auth", "true");
    properties.put("mail.smtp.starttls.enable", "true");
    properties.put("mail.smtp.host", "smtp.gmail.com");
    properties.put("mail.smtp.port", "587");
    Session session = Session.getDefaultInstance(properties,new Authenticator() {
        @Override
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication("porjetgenie.logiciel2022@gmail.com","trbqpsgfwezksylh");
        }
        
    });
    Message message = new MimeMessage(session);
    message.setSubject(subject);
    //message.setContent(other,"text/plain");
    message.setFrom(new InternetAddress(myAdress));
    message.setRecipient(Message.RecipientType.TO, new InternetAddress(email));
    message.setSentDate(new java.util.Date());
    
    // Create the message part 
    BodyPart messageBodyPart = new MimeBodyPart();
    // Fill the message
    messageBodyPart.setText(bodymessage);
    // Create a multipar message
    Multipart multipart = new MimeMultipart();
    
    // Set text message part
    multipart.addBodyPart(messageBodyPart);
    // Part two is attachment
    messageBodyPart = new MimeBodyPart();
    String filename = path;
    DataSource source = new FileDataSource(filename);
    messageBodyPart.setDataHandler(new DataHandler(source));
    messageBodyPart.setFileName(filename);
    multipart.addBodyPart(messageBodyPart);
    // Send the complete message parts
    message.setContent(multipart);
    Transport.send(message);


    JOptionPane.showMessageDialog(null, "email sent");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_generate2ActionPerformed

    private void generate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate3ActionPerformed
        // TODO add your handling code here:
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "achraf");
    pst =(PreparedStatement) conn.prepareStatement("select * from etudiants,demande_docs,convention_stages where etudiants.id=demande_docs.id_etudiant and convention_stages.id=demande_docs.id_demande and etudiants.id=?;");
    pst.setString(1, Integer.toString(id));
    rs = pst.executeQuery();
    rs.next();
    String nom_entreprise = rs.getString("nom_entreprise");
    String email_entreprise = rs.getString("email_entreprise");
    String adresse_entreprise = rs.getString("adresse_entreprise");
    String tel_entreprise = rs.getString("tel_entreprise");
    String nom = rs.getString("nom");
    String email = rs.getString("email_etudiant");
    String prenom = rs.getString("prenom");
    String filiere = rs.getString("filiere");
    String date_debut = rs.getString("date_debut");
    String date_fin = rs.getString("date_fin");
    String encadrant_entreprise = rs.getString("encadrant_entreprise");
    String encadrant_ecole = rs.getString("encadrant_ecole");
    String date = java.time.LocalDate.now().toString();
    String apogee = rs.getString("code_apogee");

    Document document = new Document("D:\\javadirectories\\convension.docx");
    Section section = document.getSections().get(0);  
    Table table = section.getTables().get(1);
    Map<String, String> map = new HashMap<String, String>(); 
   
    map.put("societe",nom_entreprise);
    map.put("societe_adress",adresse_entreprise);
    map.put("societe_email",email_entreprise);
    map.put("societe_num",tel_entreprise);
    map.put("nom",nom);
    map.put("prenom",prenom);
    map.put("filiere",filiere);
    map.put("date_debut",date_debut);
    map.put("date_fin",date_fin);
    map.put("societe_encadrant",encadrant_entreprise);
    map.put("encadrant",encadrant_ecole);
    map.put("date",date);

    /**********************************************************************/
    String path ="D:\\javadirectories\\repos\\convension_"+apogee+rs.getString("id_demande")+".pdf";
    
    replaceTextinDocumentBody(map,document);
    replaceTextinTable(map,table);
    document.saveToFile(path, FileFormat.PDF);
    JOptionPane.showMessageDialog(null, "File generated, path : "+path);
    
    //archiver
    pst =(PreparedStatement) conn.prepareStatement("UPDATE demande_docs SET status='accepté', is_archive=1 WHERE id=? ;");
    pst.setString(1, Integer.toString(id_demande));
    pst.executeUpdate();

    //open pdf fine
    File myFile = new File(path);
    Desktop.getDesktop().open(myFile);
    
    
    //variable de email
    //String email = rs.getString("email_etudiant");
    String bodymessage = "Votre convension de stage";
    String subject = "Tester email";
    String myAdress = "porjetgenie.logiciel2022@gmail.com";
    String passwordEMail = "genielogiciel";
    String contenue = bodymessage;
    String otherEmail = email;
    //send file in email code
    Properties properties = new Properties();
    properties.put("mail.smtp.auth", "true");
    properties.put("mail.smtp.starttls.enable", "true");
    properties.put("mail.smtp.host", "smtp.gmail.com");
    properties.put("mail.smtp.port", "587");
    Session session = Session.getDefaultInstance(properties,new Authenticator() {
        @Override
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication("porjetgenie.logiciel2022@gmail.com","trbqpsgfwezksylh");
        }
        
    });
    Message message = new MimeMessage(session);
    message.setSubject(subject);
    //message.setContent(other,"text/plain");
    message.setFrom(new InternetAddress(myAdress));
    message.setRecipient(Message.RecipientType.TO, new InternetAddress(email));
    message.setSentDate(new java.util.Date());
    
    // Create the message part 
    BodyPart messageBodyPart = new MimeBodyPart();
    // Fill the message
    messageBodyPart.setText(bodymessage);
    // Create a multipar message
    Multipart multipart = new MimeMultipart();
    
    // Set text message part
    multipart.addBodyPart(messageBodyPart);
    // Part two is attachment
    messageBodyPart = new MimeBodyPart();
    String filename = path;
    DataSource source = new FileDataSource(filename);
    messageBodyPart.setDataHandler(new DataHandler(source));
    messageBodyPart.setFileName(filename);
    multipart.addBodyPart(messageBodyPart);
    // Send the complete message parts
    message.setContent(multipart);
    Transport.send(message);


    JOptionPane.showMessageDialog(null, "email sent");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_generate3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pourTestFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pourTestFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pourTestFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pourTestFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pourTestFiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JButton generate;
    private javax.swing.JButton generate1;
    private javax.swing.JButton generate2;
    private javax.swing.JButton generate3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton relever_note;
    // End of variables declaration//GEN-END:variables
}
